name: Test with LocalStack

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  integration-tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
           
      # minio:
      #   image: minio/minio
      #   command: server /data
      #   env:
      #     MINIO_ROOT_USER: minio
      #     MINIO_ROOT_PASSWORD: minio123
      #   ports:
      #     - 9000:9000
       
      localstack:
        image: localstack/localstack:3
        ports:
          - 4566:4566
        env:
          SERVICES: dynamodb,s3
          DEBUG: 1

    env:
        NODE_ENV: test
        AWS_ACCESS_KEY_ID: test
        AWS_SECRET_ACCESS_KEY: test
        AWS_REGION: us-east-1
        JWT_SECRET: test
        REDIS_HOST: redis
        REDIS_PORT: 6379
        MINIO_ENDPOINT: minio
        MINIO_PORT: 9000
        MINIO_ACCESS_KEY: minio
        MINIO_SECRET_KEY: minio123
        DYNAMODB_ENDPOINT: http://localstack:4566

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        # run: npm install --legacy-peer-deps
        run: npm ci

      - name: Start MinIO container
        run: |
          docker run -d -p 9000:9000 -e MINIO_ROOT_USER=minio -e MINIO_ROOT_PASSWORD=minio123 minio/minio server /data

      - name: Start Serverless Offline
        run: |
          npx serverless offline &
          sleep 10

      - name: Run tests with LocalStack
        run: |
          echo "Test env running on LocalStack"
          npm run test
 

# 2. Verificación de servicios antes de tests
# - name: Wait for services to be ready
#   run: |
#     echo "Waiting for LocalStack..."
#     for i in {1..30}; do
#       curl -s http://localhost:4566/health | grep "running" && break
#       echo "Waiting for LocalStack... ($i/30)"
#       sleep 2
#     done
    
#     echo "Waiting for Redis..."
#     for i in {1..10}; do
#       redis-cli -h localhost ping && break
#       echo "Waiting for Redis... ($i/10)"
#       sleep 2
#     done
    
#     echo "Waiting for MinIO..."
#     for i in {1..10}; do
#       curl -s http://localhost:9000/minio/health/live && break
#       echo "Waiting for MinIO... ($i/10)"
#       sleep 2
#     done